### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by axefrog** [eteran/cpp-utilities#1]
Hi, how might I make use of your library without having to open my entire project to the world?

**Comment by eteran** [comment]
Fair enough, I think a much simpler license will work, would MIT be better suited?

**Comment by axefrog** [comment]
MIT is perfect, thanks! I'm mainly interested in the fixed-point code, as I'm doing cross-platform indie game development and floating point determinism is an issue for me.

**Comment by eteran** [comment]
Cool, If you need any beta testers for your game, I'm happy to volunteer! Hope the library helps. Of course let me know if you run into any issues :-)

**Comment by axefrog** [comment]
Sure, it's gonna be a while yet though! What's your preferred method of tracking things? Twitter? RSS? Something else?

**Comment by eteran** [comment]
Twitter works, I'm not the most active on it, but I check every now and then

**Comment by axefrog** [comment]
@NathanRidley - I'm not too focal at the moment, but I'll probably start saying a lot when I start making some real progress. I've been designing a fantasy world simulation engine for the past two years and just recently I started coding finally. Mega ambitious but I believe I've come up with a plan that will be successful. Anyway, I'll tweet when I have news. :)
