### ISSUE TITLE
Verify compiler will catch missing returns in the future

### ISSUE THREAD

**Issue by ooxi** [eteran/cpp-utilities#12]
We have to reproduce why 2d5510fdbbebdd17867c55f17f629d944e3411aa wasn't caught by our CI. Maybe the compile flags are too forgiving.

You can assign this issue to me, I'm already working on it.

**Comment by ooxi** [comment]
It was caught by the compiler, we just missed it because we didn't use `-Werror`, see e.g. [Job #4.1](https://travis-ci.org/eteran/cpp-utilities/jobs/415991181#L779)

**Comment by ooxi** [comment]
See PR #13

**Comment by eteran** [comment]
Thanks!
