### ISSUE TITLE
The remainder calculation seems to be incorrect

### ISSUE THREAD

**Issue by Jayatubi** [eteran/cpp-utilities#15]
https://github.com/eteran/cpp-utilities/blob/4c7d8fc4c09a06000c79ca8fce2b387c0a9b54ae/fixed/include/eteran/cpp-utilities/Fixed.h#L140

Why the remainder is calculated by the `t` and `denominator`? After `t <<= fractional_bits` the value of `t` would be much larger than the denominator and would cause an incorrect value of remainder.

**Comment by eteran** [comment]
the result of `t % denominator.to_raw()` is then passed to `Fixed<I,F>::from_base` which I believe does the correct rescaling.

Do you have an example of it producing the wrong answer?

**Comment by eteran** [comment]
Closing due to lack of follow up. Please re-open if you have an example demonstrating the issue.
