### ISSUE TITLE
Compilation errors about fixed<32, 32>

### ISSUE THREAD

**Issue by UFOylzj** [eteran/cpp-utilities#19]
I got some compilation errors while trying to use fixed<32, 32>:
  fixed.h(267, 60): [C2039] 'value_type': is not a member of 'numeric::detail::type_from_size<128>'
  fixed.h(80): [C2039] see declaration of 'numeric::detail::type_from_size<128>'

I think the reason is struct type_from_size dosen't have value_type. Adding such a line solves the problem.
![image](https://user-images.githubusercontent.com/6690341/149734243-df06d8ba-ed10-4b72-bfc9-4cd168828332.png)

And then I got some other compilation errors:
  fixed.h(242, 27): [C2131] expression did not evaluate to a constant
  fixed.h(399): [C2131] see reference to function template instantiation 'numeric::fixed<32,32> numeric::detail::multiply<32,32>(numeric::fixed<32,32>,numeric::fixed<32,32>,void *)' being compiled
  fixed.h(398): [C2131] while compiling class template member function 'numeric::fixed<32,32> &numeric::fixed<32,32>::operator *=(numeric::fixed<32,32>)'
  fixed.h(544): [C2131] see reference to function template instantiation 'numeric::fixed<32,32> &numeric::fixed<32,32>::operator *=(numeric::fixed<32,32>)' being compiled
  fixed.h(243, 27): [C2131] expression did not evaluate to a constant
  fixed.h(244, 27): [C2131] expression did not evaluate to a constant
  fixed.h(245, 27): [C2131] expression did not evaluate to a constant
  fixed.h(247, 25): [C2131] expression did not evaluate to a constant
  fixed.h(248, 25): [C2131] expression did not evaluate to a constant
  fixed.h(249, 25): [C2131] expression did not evaluate to a constant
  fixed.h(250, 25): [C2131] expression did not evaluate to a constant

Use const instead of constexpr solves the problem
![image](https://user-images.githubusercontent.com/6690341/149734948-a7e5cd03-f645-4abe-9939-bdad3a375286.png)

Finally, there is a warning:
  fixed.h(448, 1): [C4293] '>>': shift count negative or too big, undefined behavior

That's relatively simple, adding a bracket solves the problem
![image](https://user-images.githubusercontent.com/6690341/149735758-80c61aa4-1201-43e8-8233-ff11f54d46bd.png)

**Comment by eteran** [comment]
Interesting. Those should be `constexpr` safe. I'll look into it. What compiler are you using? some version of MSVC?

**Comment by UFOylzj** [comment]
> Interesting. Those should be `constexpr` safe. I'll look into it. What compiler are you using? some version of MSVC?

Yes. I'm using MSVC 14.28.29910

**Comment by eteran** [comment]
Yeah, it SHOULD be OK. because `constexpr` basically means it *can* be used at compile time, not that it must be, it can still be runtime code if the inputs to a `constexpr` function are runtime. Keep in mind that most of the tests for this library are `static_asserts` so clang and gcc seem pretty happy.

My guess is that MSVC doesn't support the 128-bit types with `constexpr`. I'll do some experienting and get a fix for ya.

**Comment by eteran** [comment]
Oh, LOL. This error boils down to the very first error:

```
'value_type': is not a member of 'numeric::detail::type_from_size<128>
```

I simply didn't implement 128-bit for MSVC!
So, even the most trivial usage of a 32.32 type breaks in MSVC, but not gcc or clang.

https://godbolt.org/z/zWb848cP9

Now, it is SUPPOSED to gracefully degrade, and it isn't, so I need to look into that.

**Comment by eteran** [comment]
Can you give this branch a try and see if it solves your issue, it appears to work in my (very quick and dirty) testing:

https://github.com/eteran/cpp-utilities/pull/21

**Comment by eteran** [comment]
Ah, I see. I'm re-reading your original post. You tried the same thing. (progress!).

So is MSVC 14.28 like, from Visual Studio 2015? I'm not sure that compiler had as complete/correct `constexpr` support. If it's an option for you, I'd definitely consider upgrading to the latest since community edition is free anyway.

If it's not an option, I'm sure we can make the constexpr-ness conditional on the compiler version.

**Comment by UFOylzj** [comment]
https://godbolt.org/z/cejn5M1M4

fixed<64, 64> got similar compilation errors in gcc and clang. 

https://en.cppreference.com/w/cpp/language/constexpr

cppreference says that the full-expression of a constexpr variable's initialization must be a constant expression.

**Comment by eteran** [comment]
I believe you are correct, I'll update my PR later

**Comment by eteran** [comment]
OK, Sorry for the big delay! I've ust updated my PR #21 . Can you please check it to make sure it works correctly for you and I'll then merge it!

**Comment by eteran** [comment]
Gonna merge it, I believe it fixes the issue :-). Just let me know if there is still any problems afterwards!

**Comment by UFOylzj** [comment]
Great!  It works correctly for me.
