### ISSUE TITLE
Question: Fixed Rounding

### ISSUE THREAD

**Issue by JulieCooper** [eteran/cpp-utilities#31]
What would be the suggested way to round to a particular decimal precision be using the fixed type?

**Comment by eteran** [comment]
You closed this issue, so perhaps you have already discovered the answer, but I'll give some info just in case.

Basically, this is a fundamental limitation of fixed types. It's not that it's "rounding", but that there really just isn't enough information to represent the value with a higher precision, without simply increasing the precision of the type.

Please see https://github.com/eteran/cpp-utilities/issues/2 for an in depth analysis of why this happens.
