### ISSUE TITLE
Cannot compile with Clang without disabling warnings

### ISSUE THREAD

**Issue by ooxi** [eteran/cpp-utilities#4]
First of all, thank you for your fixed math implementation! However, I cannot compile your library using Clang (5.0.1) since it warns about a GNU extension. Compiling with GCC (7.3.1) is successful, even though I have turned on pedantic warnings.

```
Fixed.h:267:61: error: in-class initializer for static data member is not a constant expression; folding it to a constant is a
      GNU extension [-Werror,-Wgnu-folding-constant]
        static const base_type fractional_mask = ~((~base_type(0)) << fractional_bits);
                                                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
```

```
Fixed.h:268:44: error: in-class initializer for static data member is not a constant expression; folding it to a constant is a
      GNU extension [-Werror,-Wgnu-folding-constant]
        static const base_type integer_mask    = ~fractional_mask;
                                                 ~^~~~~~~~~~~~~~~

```

Can you tell me what causes this issue and how it can be resolved?

**Comment by eteran** [comment]
Have you tried compiling with c++11 enabled? The following gives me no warnings or errors with `-std=c++11`

```
#include "Fixed.h"
#include <iostream>

typedef numeric::Fixed<16, 16> fixed;
fixed f;

int main() {
	f = 10.5f;
	std::cout << f << std::endl;
}
```

**Comment by ooxi** [comment]
I have compiled with `-std=c++17`, but I will try again with `-std=c++11`

**Comment by RazrFalcon** [comment]
Same here. clang 5.0.2.

**Comment by eteran** [comment]
Should be fixed now. Tested with both clang 5 and 6 using -std==11, 14 and 17

**Comment by ooxi** [comment]
I can verify that the issue is fixed for me, too!
