### ISSUE TITLE
constexpr issue with operators provided by boost

### ISSUE THREAD

**Issue by ooxi** [eteran/cpp-utilities#7]
The following code will compile:

```
constexpr bool isTrue = Fixed<16, 16>{0} < Fixed<16, 16>{1};
```

The following won't

```
constexpr bool isTrue = Fixed<16, 16>{1} > Fixed<16, 16>{0};
```

I guess the reason are the operator implementations provided by boost?

```
error: call to non-‘constexpr’ function ‘bool boost::operators_impl::operator>(const numeric::Fixed<16, 16>&, const numeric::Fixed<16, 16>&)’
```

**Comment by eteran** [comment]
Right, i guess I'll just have to implement all of the operators in a way that supports `constexpr` Hopefully with some clever template usage, I'll be able to do it without having to add a **ton** of code.

**Comment by ooxi** [comment]
Thank you very much!
